# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Remove to publis to github
#relative_permalinks: true

# Setup
title:            AverageScholar
tagline:          'An average scholar'
description:      'A blog of an average scholar'
baseurl:          ""

paginate:         5

# Custom vars
version:          2.1.0

